### ISSUE TITLE
what is <history file> ?

### ISSUE THREAD

**Issue by League2EB** [YtvwlD/hedgedoc-backup#1]
Can you clear the example about <history file> ？

thx all !

**Comment by YtvwlD** [comment]
at the top of the main page there should be a button labelled "history" or something like that. if you click on it and then on the floppy disk icon, you'll get a json which looks like this:

```json
[
  {
    "id": "some very long id",
    "text": "the title",
    "time": <timestamp>,
    "tags": [],
    "pinned": false
  },
]
```

**Comment by League2EB** [comment]
I found the history, but can you give me an example of what command is actually used?
Thank you very much

![image](https://user-images.githubusercontent.com/24560428/180840141-6f58a053-f800-4bfd-8f58-cc03629fb435.png)

**Comment by YtvwlD** [comment]
the command should be correct, i'm not sure what's going on here? can you post a (redacted) version of your json file?

**Comment by League2EB** [comment]
> the command should be correct, i'm not sure what's going on here? can you post a (redacted) version of your json file?

![](https://s2.loli.net/2022/08/01/HlEFiDNu9G27aYz.png)

this is my json , please look and try to help me , thx all

**Comment by YtvwlD** [comment]
oh, interesting. I don't have the outer `history` stuff. Let's see whether this works for you. (Feel free to reopen if it doesn't.)
